#!/usr/bin/env python3
"""
@file        seed_ragic_schema.py
@description Ragic Schema Seed：將 Phase 1 的 6 張核心 sheets
             寫入 ArangoDB da_table_info_ragic、da_field_info_ragic、
             da_table_relation_ragic Collections。
             Phase 1 Sheets：
               1. 員工管理    (configuration-file/7)   → CFG7
               2. 品項管理    (configuration-file/9)   → CFG9
               3. 交易對象    (configuration-file/10) → CFG10
               4. 倉儲位管理  (configuration-file/3)   → CFG3
               5. 組織部門    (configuration-file/2)   → CFG2
               6. 進貨單      (erp/48)                 → ERP48
@lastUpdate  2026-04-02 09:30:00
@author      Daniel Chung
@version     1.0.0
"""

import subprocess
import json

ARANGO_URL = "http://localhost:8529"
DB = "abc_desktop"
AUTH = "root:abc_desktop_2026"
TS = "2026-04-02T00:00:00Z"

# Ragic API 資訊
RAGIC_ACCOUNT = "twbraun"
RAGIC_REGION = "ap15"


def curl_post_doc(collection: str, docs: list) -> dict:
    """Bulk upsert via ArangoDB document API (overwriteMode=replace)."""
    payload = json.dumps(docs)
    r = subprocess.run(
        [
            "curl",
            "-s",
            "-u",
            AUTH,
            f"{ARANGO_URL}/_db/{DB}/_api/document/{collection}?overwriteMode=replace",
            "-X",
            "POST",
            "-H",
            "Content-Type: application/json",
            "-d",
            payload,
        ],
        capture_output=True,
        text=True,
    )
    return json.loads(r.stdout)


def insert_batch(collection: str, docs: list, label: str) -> None:
    result = curl_post_doc(collection, docs)
    errors = 0
    if isinstance(result, list):
        for i, r in enumerate(result):
            if r.get("error"):
                print(f"  ERROR [{docs[i]['_key']}]: {r.get('errorMessage', r)}")
                errors += 1
    elif isinstance(result, dict) and result.get("error"):
        print(f"  Batch error for {label}: {result}")
        errors += 1
    ok = len(docs) - errors
    print(f"  ✓ {label}: {ok}/{len(docs)} inserted/updated")


# ===========================================================================
# Helper: Build da_field_info record
# ===========================================================================


def fk_field(
    table_id: str,
    field_id: str,
    field_name: str,
    description: str,
    business_aliases: list[str],
    relation_table: str,
    relation_field: str,
    writable: bool = False,
    is_subtable: bool = False,
    subtable_key: str | None = None,
) -> dict:
    return {
        "table_id": table_id,
        "field_id": field_id,
        "field_name": field_name,
        "field_type": "VARCHAR",
        "nullable": True,
        "description": description,
        "business_aliases": business_aliases,
        "is_pk": False,
        "is_fk": True,
        "relation_table": relation_table,
        "relation_field": relation_field,
        "writable": writable,
        "is_subtable_field": is_subtable,
        "subtable_key": subtable_key,
        "status": "enabled",
    }


def make_field(
    table_id: str,
    field_id: str,
    field_name: str,
    field_type: str,
    description: str,
    business_aliases: list[str],
    writable: bool = False,
    nullable: bool = True,
    is_pk: bool = False,
    is_subtable: bool = False,
    subtable_key: str | None = None,
    is_fk: bool = False,
    relation_table: str | None = None,
    relation_field: str | None = None,
) -> dict:
    return {
        "table_id": table_id,
        "field_id": field_id,
        "field_name": field_name,
        "field_type": field_type,
        "nullable": nullable,
        "description": description,
        "business_aliases": business_aliases,
        "is_pk": is_pk,
        "is_fk": is_fk,
        "relation_table": relation_table,
        "relation_field": relation_field,
        "writable": writable,
        "is_subtable_field": is_subtable,
        "subtable_key": subtable_key,
        "status": "enabled",
    }


# ===========================================================================
# §1 TABLE INFO
# ===========================================================================

tables = [
    {
        "_key": "CFG2_DEPT",
        "table_id": "CFG2_DEPT",
        "table_name": "組織部門",
        "tab": "configuration-file",
        "sheet_key": "2",
        "module": "BASE",
        "description": "組織部門主檔，含部門階層與子表格員工清單",
        "s3_path": "s3://ragic/departments/",
        "primary_keys": ["_ragicId"],
        "partition_keys": [],
        "record_count": 0,
        "data_source": "ragic",
        "status": "enabled",
        "version": 1,
        "created_at": TS,
        "updated_at": TS,
        "updated_by": "system",
    },
    {
        "_key": "CFG3_WAREHOUSE",
        "table_id": "CFG3_WAREHOUSE",
        "table_name": "倉儲位管理",
        "tab": "configuration-file",
        "sheet_key": "3",
        "module": "BASE",
        "description": "倉庫與儲位主檔，含子表格儲位清單",
        "s3_path": "s3://ragic/warehouses/",
        "primary_keys": ["_ragicId"],
        "partition_keys": [],
        "record_count": 0,
        "data_source": "ragic",
        "status": "enabled",
        "version": 1,
        "created_at": TS,
        "updated_at": TS,
        "updated_by": "system",
    },
    {
        "_key": "CFG7_EMPLOYEE",
        "table_id": "CFG7_EMPLOYEE",
        "table_name": "員工管理",
        "tab": "configuration-file",
        "sheet_key": "7",
        "module": "BASE",
        "description": "員工主檔，含緊急聯絡人、教育訓練、兼職記錄等子表格",
        "s3_path": "s3://ragic/employees/",
        "primary_keys": ["_ragicId"],
        "partition_keys": [],
        "record_count": 0,
        "data_source": "ragic",
        "status": "enabled",
        "version": 1,
        "created_at": TS,
        "updated_at": TS,
        "updated_by": "system",
    },
    {
        "_key": "CFG9_ITEM",
        "table_id": "CFG9_ITEM",
        "table_name": "品項管理",
        "tab": "configuration-file",
        "sheet_key": "9",
        "module": "BASE",
        "description": "品項/物料主檔，含採購、包裝規格、供應商等完整屬性",
        "s3_path": "s3://ragic/items/",
        "primary_keys": ["_ragicId"],
        "partition_keys": [],
        "record_count": 0,
        "data_source": "ragic",
        "status": "enabled",
        "version": 1,
        "created_at": TS,
        "updated_at": TS,
        "updated_by": "system",
    },
    {
        "_key": "CFG10_VENDOR",
        "table_id": "CFG10_VENDOR",
        "table_name": "交易對象(客戶/供應商)",
        "tab": "configuration-file",
        "sheet_key": "10",
        "module": "BASE",
        "description": "交易對象（客戶/供應商）主檔，含聯絡人、出貨資訊等子表格",
        "s3_path": "s3://ragic/vendors/",
        "primary_keys": ["_ragicId"],
        "partition_keys": [],
        "record_count": 0,
        "data_source": "ragic",
        "status": "enabled",
        "version": 1,
        "created_at": TS,
        "updated_at": TS,
        "updated_by": "system",
    },
    {
        "_key": "ERP48_PURCHASE_ORDER",
        "table_id": "ERP48_PURCHASE_ORDER",
        "table_name": "進貨單",
        "tab": "erp",
        "sheet_key": "48",
        "module": "PUR",
        "description": "進貨單表頭，含供應商、金額、發票等資訊，含子表格進貨明細",
        "s3_path": "s3://ragic/purchase_orders/",
        "primary_keys": ["_ragicId"],
        "partition_keys": ["date_year_month"],
        "record_count": 0,
        "data_source": "ragic",
        "status": "enabled",
        "version": 1,
        "created_at": TS,
        "updated_at": TS,
        "updated_by": "system",
    },
]

# Add common system fields to all tables
SYSTEM_FIELDS = {
    "_ragicId": {
        "field_id": "_ragicId",
        "field_name": "Ragic Record ID",
        "field_type": "VARCHAR",
        "description": "Ragic 記錄唯一識別碼",
        "business_aliases": ["記錄ID", "Record ID"],
        "is_pk": True,
        "nullable": False,
        "writable": False,
    },
    "105": {
        "field_id": "105",
        "field_name": "建立日期",
        "field_type": "DATE",
        "description": "系統欄位：建立日期",
        "business_aliases": ["建立日"],
        "is_pk": False,
        "nullable": False,
        "writable": False,
    },
    "109": {
        "field_id": "109",
        "field_name": "最後更新日期",
        "field_type": "DATE",
        "description": "系統欄位：最後更新日期",
        "business_aliases": ["更新日"],
        "is_pk": False,
        "nullable": False,
        "writable": False,
    },
}

# ===========================================================================
# §2 FIELD INFO
# ===========================================================================

fields: list[dict] = []

for t in tables:
    table_id = t["table_id"]
    # Add system fields
    for sys_field_id, sys_field in SYSTEM_FIELDS.items():
        fields.append(
            {
                "_key": f"{table_id}_{sys_field_id}",
                "table_id": table_id,
                **sys_field,
                "is_fk": False,
                "relation_table": None,
                "relation_field": None,
                "is_subtable_field": False,
                "subtable_key": None,
                "status": "enabled",
            }
        )

# ---- CFG2: 組織部門 ----
CFG2_FIELDS = [
    make_field(
        "CFG2_DEPT",
        "1015395",
        "建檔代碼",
        "VARCHAR",
        "連結至編碼原則定義",
        ["建檔代碼"],
        writable=True,
    ),
    make_field(
        "CFG2_DEPT",
        "1015391",
        "部門編號",
        "VARCHAR",
        "自動編號：{建檔代碼}-000",
        ["部門編號"],
        writable=False,
    ),
    make_field(
        "CFG2_DEPT",
        "1015392",
        "部門名稱",
        "VARCHAR",
        "不可重複必填",
        ["部門名"],
        writable=True,
        nullable=False,
    ),
    make_field(
        "CFG2_DEPT",
        "1022588",
        "上級部門",
        "VARCHAR",
        "上層部門名稱",
        ["上層部門"],
        writable=True,
    ),
    make_field(
        "CFG2_DEPT",
        "1015394",
        "建檔類型",
        "VARCHAR",
        "預設值：組織部門建檔",
        [],
        writable=True,
    ),
]
fields.extend(CFG2_FIELDS)

# 子表格：員工清單 (1015442)
CFG2_SUB_FIELDS = [
    make_field(
        "CFG2_DEPT",
        "1015428",
        "員工編號",
        "VARCHAR",
        "自動編號",
        ["員工編號"],
        is_subtable=True,
        subtable_key="1015442",
    ),
    make_field(
        "CFG2_DEPT",
        "1015429",
        "員工姓名",
        "VARCHAR",
        "必填",
        ["員工名"],
        writable=True,
        nullable=False,
        is_subtable=True,
        subtable_key="1015442",
    ),
    make_field(
        "CFG2_DEPT",
        "1015443",
        "任職狀態",
        "VARCHAR",
        "在職/離職/留職停薪",
        ["狀態"],
        writable=True,
        is_subtable=True,
        subtable_key="1015442",
    ),
    make_field(
        "CFG2_DEPT",
        "1015498",
        "聘僱類型",
        "VARCHAR",
        "正職/約聘/...",
        ["僱用類型"],
        writable=True,
        is_subtable=True,
        subtable_key="1015442",
    ),
    make_field(
        "CFG2_DEPT",
        "1015496",
        "職稱",
        "VARCHAR",
        "職位名稱",
        ["職稱"],
        writable=True,
        is_subtable=True,
        subtable_key="1015442",
    ),
    make_field(
        "CFG2_DEPT",
        "1015525",
        "分機",
        "VARCHAR",
        "分機號碼",
        ["分機"],
        writable=True,
        is_subtable=True,
        subtable_key="1015442",
    ),
    make_field(
        "CFG2_DEPT",
        "1015494",
        "所屬部門",
        "VARCHAR",
        "唯讀：載入部門名稱",
        [],
        writable=False,
        is_subtable=True,
        subtable_key="1015442",
    ),
    make_field(
        "CFG2_DEPT",
        "1015499",
        "班別",
        "VARCHAR",
        "班別",
        [],
        writable=True,
        is_subtable=True,
        subtable_key="1015442",
    ),
    make_field(
        "CFG2_DEPT",
        "1022595",
        "兼任部門名稱1",
        "VARCHAR",
        "兼任部門",
        [],
        writable=False,
        is_subtable=True,
        subtable_key="1015442",
    ),
    make_field(
        "CFG2_DEPT",
        "1022597",
        "兼任部門名稱2",
        "VARCHAR",
        "兼任部門2",
        [],
        writable=False,
        is_subtable=True,
        subtable_key="1015442",
    ),
    # 代理人（連結到員工）
    fk_field(
        "CFG2_DEPT",
        "1015500",
        "代理人編號",
        "代理人員工編號",
        ["代理人"],
        relation_table="CFG7_EMPLOYEE",
        relation_field="1015428",
        writable=True,
        is_subtable=True,
        subtable_key="1015442",
    ),
    make_field(
        "CFG2_DEPT",
        "1015501",
        "代理人",
        "VARCHAR",
        "唯讀：載入員工姓名",
        [],
        writable=False,
        is_subtable=True,
        subtable_key="1015442",
    ),
]
fields.extend(CFG2_SUB_FIELDS)

# ---- CFG3: 倉儲位管理 ----
CFG3_FIELDS = [
    make_field(
        "CFG3_WAREHOUSE",
        "1015396",
        "建檔代碼",
        "VARCHAR",
        "連結至編碼原則定義，必填",
        ["建檔代碼"],
        writable=True,
    ),
    make_field(
        "CFG3_WAREHOUSE",
        "1015398",
        "倉庫編碼",
        "VARCHAR",
        "自動編號：{建檔代碼}-000",
        ["倉庫編碼"],
        writable=False,
    ),
    make_field(
        "CFG3_WAREHOUSE",
        "1015397",
        "倉庫名稱",
        "VARCHAR",
        "不可重複必填",
        ["倉庫名"],
        writable=True,
        nullable=False,
    ),
    make_field(
        "CFG3_WAREHOUSE",
        "1015399",
        "建檔類型",
        "VARCHAR",
        "預設值：倉儲建檔",
        [],
        writable=True,
    ),
]
fields.extend(CFG3_FIELDS)

# 子表格：儲位清單 (1015411)
CFG3_SUB_FIELDS = [
    make_field(
        "CFG3_WAREHOUSE",
        "1015402",
        "儲位序號",
        "VARCHAR",
        "儲位順序",
        [],
        writable=True,
        is_subtable=True,
        subtable_key="1015411",
    ),
    make_field(
        "CFG3_WAREHOUSE",
        "1015403",
        "儲位名稱",
        "VARCHAR",
        "儲位描述",
        [],
        writable=True,
        is_subtable=True,
        subtable_key="1015411",
    ),
    make_field(
        "CFG3_WAREHOUSE",
        "1015405",
        "料架序號",
        "VARCHAR",
        "料架順序",
        [],
        writable=True,
        is_subtable=True,
        subtable_key="1015411",
    ),
    make_field(
        "CFG3_WAREHOUSE",
        "1015406",
        "料架名稱",
        "VARCHAR",
        "料架描述",
        [],
        writable=True,
        is_subtable=True,
        subtable_key="1015411",
    ),
    make_field(
        "CFG3_WAREHOUSE",
        "1015407",
        "倉儲名稱",
        "VARCHAR",
        "唯讀：公式計算",
        [],
        writable=False,
        is_subtable=True,
        subtable_key="1015411",
    ),
    make_field(
        "CFG3_WAREHOUSE",
        "1015408",
        "倉儲編碼",
        "VARCHAR",
        "唯讀：公式計算",
        ["編碼"],
        writable=False,
        is_subtable=True,
        subtable_key="1015411",
    ),
    make_field(
        "CFG3_WAREHOUSE",
        "1016686",
        "倉儲QR-code",
        "VARCHAR",
        "條碼",
        ["QR"],
        writable=True,
        is_subtable=True,
        subtable_key="1015411",
    ),
    make_field(
        "CFG3_WAREHOUSE",
        "1015401",
        "儲位代碼",
        "VARCHAR",
        "隱藏：載入",
        [],
        writable=True,
        is_subtable=True,
        subtable_key="1015411",
    ),
    make_field(
        "CFG3_WAREHOUSE",
        "1020233",
        "儲位",
        "VARCHAR",
        "連結至編碼原則",
        [],
        writable=True,
        is_subtable=True,
        subtable_key="1015411",
    ),
    make_field(
        "CFG3_WAREHOUSE",
        "1015404",
        "料架代碼",
        "VARCHAR",
        "隱藏：載入",
        [],
        writable=True,
        is_subtable=True,
        subtable_key="1015411",
    ),
    make_field(
        "CFG3_WAREHOUSE",
        "1020234",
        "料架",
        "VARCHAR",
        "連結至編碼原則",
        [],
        writable=True,
        is_subtable=True,
        subtable_key="1015411",
    ),
]
fields.extend(CFG3_SUB_FIELDS)

# ---- CFG7: 員工管理 ----
CFG7_FIELDS = [
    make_field(
        "CFG7_EMPLOYEE",
        "1015427",
        "建檔代碼",
        "VARCHAR",
        "連結至編碼原則定義，必填",
        ["建檔代碼"],
        writable=True,
    ),
    make_field(
        "CFG7_EMPLOYEE",
        "1015428",
        "員工編號",
        "VARCHAR",
        "自動編號，不可重複",
        ["員工編號"],
        writable=False,
    ),
    make_field(
        "CFG7_EMPLOYEE",
        "1015429",
        "員工姓名",
        "VARCHAR",
        "不可重複必填",
        ["姓名"],
        writable=True,
        nullable=False,
    ),
    make_field(
        "CFG7_EMPLOYEE", "1015430", "性別", "VARCHAR", "男/女", ["性別"], writable=True
    ),
    make_field(
        "CFG7_EMPLOYEE",
        "1015437",
        "手機號碼",
        "VARCHAR",
        "行動電話",
        ["手機"],
        writable=True,
    ),
    make_field(
        "CFG7_EMPLOYEE",
        "1015438",
        "電話號碼",
        "VARCHAR",
        "室內電話",
        ["電話"],
        writable=True,
    ),
    make_field(
        "CFG7_EMPLOYEE",
        "1015439",
        "E-mail",
        "VARCHAR",
        "Email，必填",
        ["Email"],
        writable=True,
        nullable=False,
    ),
    make_field(
        "CFG7_EMPLOYEE",
        "1015443",
        "任職狀態",
        "VARCHAR",
        "在職/離職/留職停薪",
        ["狀態"],
        writable=True,
    ),
    make_field(
        "CFG7_EMPLOYEE",
        "1015444",
        "到職日期",
        "DATE",
        "入職日期",
        ["到職日"],
        writable=True,
    ),
    make_field(
        "CFG7_EMPLOYEE",
        "1015445",
        "離職日期",
        "DATE",
        "離職日期",
        ["離職日"],
        writable=True,
    ),
    make_field(
        "CFG7_EMPLOYEE",
        "1015433",
        "出生日期",
        "DATE",
        "員工生日",
        ["生日"],
        writable=True,
    ),
    make_field(
        "CFG7_EMPLOYEE",
        "1015436",
        "身份證字號",
        "VARCHAR",
        "身份證字號",
        ["身分證"],
        writable=True,
    ),
    make_field(
        "CFG7_EMPLOYEE",
        "1015440",
        "戶籍地址",
        "VARCHAR",
        "戶籍地址",
        ["戶籍"],
        writable=True,
    ),
    make_field(
        "CFG7_EMPLOYEE",
        "1015441",
        "現居地址",
        "VARCHAR",
        "通訊地址",
        ["地址"],
        writable=True,
    ),
    make_field(
        "CFG7_EMPLOYEE",
        "1015432",
        "英文名",
        "VARCHAR",
        "員工英文名",
        ["英文名"],
        writable=True,
    ),
    make_field(
        "CFG7_EMPLOYEE",
        "1015434",
        "年齡",
        "DECIMAL",
        "唯讀：公式計算",
        ["年齡"],
        writable=False,
    ),
    make_field(
        "CFG7_EMPLOYEE",
        "1015477",
        "教育程度",
        "VARCHAR",
        "學歷",
        ["學歷"],
        writable=True,
    ),
    make_field(
        "CFG7_EMPLOYEE",
        "1015498",
        "聘僱類型",
        "VARCHAR",
        "正職/約聘/工讀生/...",
        ["類型"],
        writable=True,
    ),
    make_field(
        "CFG7_EMPLOYEE",
        "1015496",
        "職稱",
        "VARCHAR",
        "職位名稱",
        ["職稱"],
        writable=True,
    ),
    make_field(
        "CFG7_EMPLOYEE",
        "1015480",
        "任職年資",
        "DECIMAL",
        "唯讀：公式計算（年）",
        ["年資"],
        writable=False,
    ),
    make_field(
        "CFG7_EMPLOYEE",
        "1015525",
        "分機",
        "VARCHAR",
        "公司分機",
        ["分機"],
        writable=True,
    ),
    make_field(
        "CFG7_EMPLOYEE",
        "1015505",
        "薪資類型",
        "VARCHAR",
        "月薪/日薪/時薪",
        ["薪資類型"],
        writable=True,
    ),
    make_field(
        "CFG7_EMPLOYEE",
        "1015506",
        "基本薪資",
        "DECIMAL",
        "基本工資",
        ["薪資"],
        writable=True,
    ),
    make_field(
        "CFG7_EMPLOYEE",
        "1015507",
        "薪資發放方式",
        "VARCHAR",
        "領現/匯款",
        ["發放方式"],
        writable=True,
    ),
    make_field(
        "CFG7_EMPLOYEE",
        "1015511",
        "是否自行提繳退休金",
        "VARCHAR",
        "勾選：No/Yes",
        ["退休金"],
        writable=True,
    ),
    make_field(
        "CFG7_EMPLOYEE",
        "1015516",
        "銀行代號",
        "VARCHAR",
        "連結至銀行代碼表",
        ["銀行"],
        writable=True,
    ),
    make_field(
        "CFG7_EMPLOYEE",
        "1015518",
        "分行帳號",
        "VARCHAR",
        "分行名稱",
        ["分行"],
        writable=True,
    ),
    make_field(
        "CFG7_EMPLOYEE",
        "1015520",
        "帳號",
        "VARCHAR",
        "銀行帳號",
        ["帳號"],
        writable=True,
    ),
    make_field(
        "CFG7_EMPLOYEE",
        "1015524",
        "備註",
        "VARCHAR",
        "備註說明",
        ["備註"],
        writable=True,
    ),
    # 部門連結
    fk_field(
        "CFG7_EMPLOYEE",
        "1015495",
        "所屬部門編號",
        "部門編號",
        ["部門"],
        relation_table="CFG2_DEPT",
        relation_field="1015391",
        writable=True,
    ),
    make_field(
        "CFG7_EMPLOYEE",
        "1015494",
        "所屬部門名稱",
        "VARCHAR",
        "唯讀：載入部門名稱",
        [],
        writable=False,
    ),
    # 兼任部門
    fk_field(
        "CFG7_EMPLOYEE",
        "1022594",
        "兼任部門編號1",
        "兼任部門編號",
        ["兼任部門"],
        relation_table="CFG2_DEPT",
        relation_field="1015391",
        writable=True,
    ),
    fk_field(
        "CFG7_EMPLOYEE",
        "1022596",
        "兼任部門編號2",
        "兼任部門編號2",
        ["兼任部門2"],
        relation_table="CFG2_DEPT",
        relation_field="1015391",
        writable=True,
    ),
    make_field(
        "CFG7_EMPLOYEE",
        "1022595",
        "兼任部門名稱1",
        "VARCHAR",
        "唯讀：載入",
        [],
        writable=False,
    ),
    make_field(
        "CFG7_EMPLOYEE",
        "1022597",
        "兼任部門名稱2",
        "VARCHAR",
        "唯讀：載入",
        [],
        writable=False,
    ),
    # 代理人
    fk_field(
        "CFG7_EMPLOYEE",
        "1015500",
        "代理人編號",
        "代理人員工編號",
        ["代理人"],
        relation_table="CFG7_EMPLOYEE",
        relation_field="1015428",
        writable=True,
    ),
    make_field(
        "CFG7_EMPLOYEE",
        "1015501",
        "代理人",
        "VARCHAR",
        "唯讀：載入員工姓名",
        [],
        writable=False,
    ),
]
fields.extend(CFG7_FIELDS)

# 子表格：緊急聯絡人 (1015530)
CFG7_EMERGENCY_SUB = [
    make_field(
        "CFG7_EMPLOYEE",
        "1015526",
        "緊急聯絡人",
        "VARCHAR",
        "緊急聯絡人姓名",
        [],
        writable=True,
        is_subtable=True,
        subtable_key="1015530",
    ),
    make_field(
        "CFG7_EMPLOYEE",
        "1015527",
        "電話",
        "VARCHAR",
        "聯絡電話",
        [],
        writable=True,
        is_subtable=True,
        subtable_key="1015530",
    ),
    make_field(
        "CFG7_EMPLOYEE",
        "1015528",
        "手機",
        "VARCHAR",
        "行動電話",
        [],
        writable=True,
        is_subtable=True,
        subtable_key="1015530",
    ),
    make_field(
        "CFG7_EMPLOYEE",
        "1015529",
        "關係",
        "VARCHAR",
        "與員工關係",
        [],
        writable=True,
        is_subtable=True,
        subtable_key="1015530",
    ),
]
fields.extend(CFG7_EMERGENCY_SUB)

# 子表格：教育訓練 (1019512)
CFG7_TRAINING_SUB = [
    make_field(
        "CFG7_EMPLOYEE",
        "1020214",
        "年度",
        "VARCHAR",
        "年度",
        [],
        writable=False,
        is_subtable=True,
        subtable_key="1019512",
    ),
    make_field(
        "CFG7_EMPLOYEE",
        "1019516",
        "課程名稱",
        "VARCHAR",
        "訓練課程",
        [],
        writable=False,
        is_subtable=True,
        subtable_key="1019512",
    ),
    make_field(
        "CFG7_EMPLOYEE",
        "1019517",
        "時數",
        "DECIMAL",
        "訓練時數",
        [],
        writable=False,
        is_subtable=True,
        subtable_key="1019512",
    ),
    make_field(
        "CFG7_EMPLOYEE",
        "1019509",
        "結果(勾選)",
        "VARCHAR",
        "是否完成",
        [],
        writable=False,
        is_subtable=True,
        subtable_key="1019512",
    ),
]
fields.extend(CFG7_TRAINING_SUB)

# 子表格：異動記錄 (1022601)
CFG7_CHANGE_SUB = [
    make_field(
        "CFG7_EMPLOYEE",
        "1022598",
        "開始日期",
        "DATE",
        "異動開始日期",
        [],
        writable=True,
        is_subtable=True,
        subtable_key="1022601",
    ),
    make_field(
        "CFG7_EMPLOYEE",
        "1022599",
        "結束日期",
        "DATE",
        "異動結束日期",
        [],
        writable=True,
        is_subtable=True,
        subtable_key="1022601",
    ),
    make_field(
        "CFG7_EMPLOYEE",
        "1022600",
        "異動原因",
        "VARCHAR",
        "留停原因",
        [],
        writable=True,
        is_subtable=True,
        subtable_key="1022601",
    ),
]
fields.extend(CFG7_CHANGE_SUB)

# ---- CFG9: 品項管理 ----
CFG9_FIELDS = [
    make_field(
        "CFG9_ITEM",
        "1015229",
        "品項版次",
        "VARCHAR",
        "自動編號，不可重複",
        ["版次"],
        writable=False,
    ),
    make_field(
        "CFG9_ITEM",
        "1015486",
        "品項編碼",
        "VARCHAR",
        "連結至品項編碼設定",
        ["品項編碼"],
        writable=True,
    ),
    make_field(
        "CFG9_ITEM",
        "1015483",
        "品項名稱",
        "VARCHAR",
        "唯讀：載入，不可重複",
        ["品名", "品項"],
        writable=False,
    ),
    make_field(
        "CFG9_ITEM",
        "1015225",
        "規格說明",
        "VARCHAR",
        "品項規格描述",
        ["規格"],
        writable=True,
    ),
    make_field(
        "CFG9_ITEM",
        "1015223",
        "版次說明",
        "VARCHAR",
        "版本備註",
        ["版次說明"],
        writable=True,
    ),
    make_field(
        "CFG9_ITEM",
        "1015328",
        "品項版次(自動)",
        "VARCHAR",
        "自動產生：{品項編碼}-00",
        ["版次"],
        writable=False,
    ),
    make_field(
        "CFG9_ITEM",
        "1015224",
        "品項英文名",
        "VARCHAR",
        "英文名稱",
        ["英文名"],
        writable=True,
    ),
    make_field(
        "CFG9_ITEM",
        "1022774",
        "品項別名",
        "VARCHAR",
        "別名/俗名",
        ["別名"],
        writable=True,
    ),
    make_field(
        "CFG9_ITEM",
        "1016531",
        "非追",
        "VARCHAR",
        "隱藏：品項類型標記",
        [],
        writable=False,
    ),
    make_field(
        "CFG9_ITEM",
        "1015230",
        "附件",
        "VARCHAR",
        "多檔案上傳（URL）",
        ["附件"],
        writable=True,
    ),
    make_field(
        "CFG9_ITEM",
        "1018425",
        "主類別",
        "VARCHAR",
        "原料/半成品/成品/商品/...",
        ["類別"],
        writable=True,
    ),
    make_field(
        "CFG9_ITEM", "1018426", "副類別", "VARCHAR", "副類別", ["副類別"], writable=True
    ),
    make_field(
        "CFG9_ITEM",
        "1018427",
        "產品包裝規格重量",
        "VARCHAR",
        "包裝重量",
        ["重量"],
        writable=True,
    ),
    make_field(
        "CFG9_ITEM",
        "1018428",
        "產品包裝規格重量單位",
        "VARCHAR",
        "g/kg",
        ["重量單位"],
        writable=True,
    ),
    make_field(
        "CFG9_ITEM",
        "1018429",
        "產品包裝規格單位",
        "VARCHAR",
        "袋/瓶/桶/罐/盒/包/...",
        ["包裝"],
        writable=True,
    ),
    make_field(
        "CFG9_ITEM",
        "1018430",
        "標準售價(未稅)",
        "DECIMAL",
        "牌價（未含稅）",
        ["售價"],
        writable=True,
    ),
    make_field(
        "CFG9_ITEM",
        "1018431",
        "標準售價(含稅)",
        "DECIMAL",
        "牌價（含稅）",
        ["含稅售價"],
        writable=True,
    ),
    make_field(
        "CFG9_ITEM",
        "1018432",
        "採購單價(未稅)",
        "DECIMAL",
        "進價（未含稅）",
        ["進價"],
        writable=True,
    ),
    make_field(
        "CFG9_ITEM",
        "1018433",
        "採購單價(含稅)",
        "DECIMAL",
        "進價（含稅）",
        ["含稅進價"],
        writable=True,
    ),
    make_field(
        "CFG9_ITEM",
        "1018434",
        "即時庫存",
        "DECIMAL",
        "當前庫存量",
        ["庫存"],
        writable=True,
    ),
    make_field(
        "CFG9_ITEM",
        "1018435",
        "安全庫存",
        "DECIMAL",
        "最低安全存量",
        ["安全存量"],
        writable=True,
    ),
    make_field(
        "CFG9_ITEM",
        "1018436",
        "品項編碼(載入)",
        "VARCHAR",
        "唯讀：載入品項版次",
        ["品項"],
        writable=False,
    ),
    make_field(
        "CFG9_ITEM",
        "1018420",
        "主供應商編碼",
        "VARCHAR",
        "主要供應商",
        ["供應商"],
        writable=True,
    ),
    make_field(
        "CFG9_ITEM",
        "1018422",
        "主供應商名稱",
        "VARCHAR",
        "唯讀：載入",
        ["供應商名"],
        writable=False,
    ),
    make_field(
        "CFG9_ITEM",
        "1018437",
        "主倉庫編碼",
        "VARCHAR",
        "主要存放倉庫",
        ["倉庫"],
        writable=True,
    ),
    make_field(
        "CFG9_ITEM",
        "1018439",
        "主倉庫名稱",
        "VARCHAR",
        "唯讀：載入",
        ["倉庫名"],
        writable=False,
    ),
    make_field(
        "CFG9_ITEM", "1018440", "主儲位", "VARCHAR", "存放儲位", ["儲位"], writable=True
    ),
    make_field(
        "CFG9_ITEM",
        "1018441",
        "主儲位名稱",
        "VARCHAR",
        "唯讀：載入",
        ["儲位名"],
        writable=False,
    ),
    make_field(
        "CFG9_ITEM", "1015423", "備註", "VARCHAR", "備註說明", ["備註"], writable=True
    ),
    # 供應商連結
    fk_field(
        "CFG9_ITEM",
        "1022528",
        "供應商編號",
        "供應商編號",
        ["供應商"],
        relation_table="CFG10_VENDOR",
        relation_field="1015577",
        writable=True,
    ),
    make_field(
        "CFG9_ITEM",
        "1022529",
        "供應商名稱",
        "VARCHAR",
        "唯讀：載入供應商名稱",
        [],
        writable=False,
    ),
]
fields.extend(CFG9_FIELDS)

# ---- CFG10: 交易對象(客戶/供應商) ----
CFG10_FIELDS = [
    make_field(
        "CFG10_VENDOR",
        "1015616",
        "主表單Key(建檔對象)",
        "VARCHAR",
        "主表單Key",
        [],
        writable=False,
    ),
    make_field(
        "CFG10_VENDOR",
        "1015577",
        "交易對象編碼",
        "VARCHAR",
        "自動編號，不可重複",
        ["對象編碼"],
        writable=False,
    ),
    make_field(
        "CFG10_VENDOR",
        "1015578",
        "交易對象全稱",
        "VARCHAR",
        "不可重複必填",
        ["全稱", "名稱"],
        writable=True,
        nullable=False,
    ),
    make_field(
        "CFG10_VENDOR",
        "1015579",
        "交易對象簡稱",
        "VARCHAR",
        "簡稱",
        ["簡稱"],
        writable=True,
    ),
    make_field(
        "CFG10_VENDOR",
        "1019926",
        "客戶屬性",
        "VARCHAR",
        "下游業者/消費者",
        ["客戶屬性"],
        writable=True,
    ),
    make_field(
        "CFG10_VENDOR",
        "1019994",
        "供應商屬性",
        "VARCHAR",
        "原材料/消耗性材料/...",
        ["供應商屬性"],
        writable=True,
    ),
    make_field(
        "CFG10_VENDOR",
        "1015626",
        "交易狀態",
        "VARCHAR",
        "評估中/交易中/停止交易",
        ["狀態"],
        writable=True,
    ),
    make_field(
        "CFG10_VENDOR",
        "1015589",
        "負責人",
        "VARCHAR",
        "負責人姓名",
        ["負責人"],
        writable=True,
    ),
    make_field(
        "CFG10_VENDOR",
        "1015611",
        "部門/職稱",
        "VARCHAR",
        "部門與職位",
        ["部門"],
        writable=True,
    ),
    make_field(
        "CFG10_VENDOR",
        "1015604",
        "聯絡人",
        "VARCHAR",
        "主要聯絡人",
        ["聯絡人"],
        writable=True,
    ),
    make_field(
        "CFG10_VENDOR",
        "1015605",
        "電話",
        "VARCHAR",
        "聯絡電話",
        ["電話"],
        writable=True,
    ),
    make_field(
        "CFG10_VENDOR",
        "1015581",
        "統一編號",
        "VARCHAR",
        "統一發票號碼",
        ["統編"],
        writable=True,
    ),
    make_field(
        "CFG10_VENDOR",
        "1015593",
        "食品業者登錄字號",
        "VARCHAR",
        "食品業者登錄",
        ["登錄字號"],
        writable=True,
    ),
    make_field(
        "CFG10_VENDOR",
        "1015594",
        "未輸入登錄字號理由",
        "VARCHAR",
        "原因選項",
        ["理由"],
        writable=True,
    ),
    make_field(
        "CFG10_VENDOR", "1016482", "縣市", "VARCHAR", "縣市", ["縣市"], writable=True
    ),
    make_field(
        "CFG10_VENDOR", "1016483", "區域", "VARCHAR", "鄉鎮區", ["區域"], writable=True
    ),
    make_field(
        "CFG10_VENDOR",
        "1016484",
        "地址",
        "VARCHAR",
        "完整地址",
        ["地址"],
        writable=True,
    ),
    make_field(
        "CFG10_VENDOR",
        "1016486",
        "傳真",
        "VARCHAR",
        "傳真號碼",
        ["傳真"],
        writable=True,
    ),
    make_field(
        "CFG10_VENDOR", "1016487", "Email", "VARCHAR", "Email", ["Email"], writable=True
    ),
    make_field(
        "CFG10_VENDOR", "1016489", "網址", "VARCHAR", "網站", ["網址"], writable=True
    ),
    make_field(
        "CFG10_VENDOR",
        "1015599",
        "交易幣別",
        "VARCHAR",
        "交易幣別",
        ["幣別"],
        writable=True,
    ),
    make_field(
        "CFG10_VENDOR",
        "1015600",
        "付款條件",
        "VARCHAR",
        "月結30天/現結/...",
        ["付款條件"],
        writable=True,
    ),
    make_field(
        "CFG10_VENDOR",
        "1015602",
        "信用額度",
        "DECIMAL",
        "信用額度上限",
        ["額度"],
        writable=True,
    ),
    make_field(
        "CFG10_VENDOR",
        "1015622",
        "備註",
        "VARCHAR",
        "備註說明",
        ["備註"],
        writable=True,
    ),
]
fields.extend(CFG10_FIELDS)

# 子表格：出貨聯絡資訊 (子表格Key見 RagicTableSchema)
CFG10_SHIP_SUB = [
    make_field(
        "CFG10_VENDOR",
        "1015617",
        "聯絡人姓名",
        "VARCHAR",
        "出貨聯絡人",
        [],
        writable=True,
        is_subtable=True,
        subtable_key="1015617",
    ),
    make_field(
        "CFG10_VENDOR",
        "1015618",
        "部門/職稱",
        "VARCHAR",
        "部門與職位",
        [],
        writable=True,
        is_subtable=True,
        subtable_key="1015617",
    ),
    make_field(
        "CFG10_VENDOR",
        "1015619",
        "電話",
        "VARCHAR",
        "聯絡電話",
        [],
        writable=True,
        is_subtable=True,
        subtable_key="1015617",
    ),
    make_field(
        "CFG10_VENDOR",
        "1015620",
        "手機",
        "VARCHAR",
        "行動電話",
        [],
        writable=True,
        is_subtable=True,
        subtable_key="1015617",
    ),
    make_field(
        "CFG10_VENDOR",
        "1015621",
        "傳真",
        "VARCHAR",
        "傳真",
        [],
        writable=True,
        is_subtable=True,
        subtable_key="1015617",
    ),
]
fields.extend(CFG10_SHIP_SUB)

# 子表格：銀行帳戶 (子表格Key見 RagicTableSchema)
CFG10_BANK_SUB = [
    make_field(
        "CFG10_VENDOR",
        "1015622",
        "銀行名稱",
        "VARCHAR",
        "銀行名稱",
        [],
        writable=True,
        is_subtable=True,
        subtable_key="1015622",
    ),
    make_field(
        "CFG10_VENDOR",
        "1015623",
        "分行名稱",
        "VARCHAR",
        "分行",
        [],
        writable=True,
        is_subtable=True,
        subtable_key="1015622",
    ),
    make_field(
        "CFG10_VENDOR",
        "1015624",
        "帳號",
        "VARCHAR",
        "銀行帳號",
        [],
        writable=True,
        is_subtable=True,
        subtable_key="1015622",
    ),
    make_field(
        "CFG10_VENDOR",
        "1015625",
        "戶名",
        "VARCHAR",
        "帳戶名稱",
        [],
        writable=True,
        is_subtable=True,
        subtable_key="1015622",
    ),
]
fields.extend(CFG10_BANK_SUB)

# ---- ERP48: 進貨單 ----
ERP48_FIELDS = [
    make_field(
        "ERP48_PURCHASE_ORDER",
        "1023120",
        "進貨單號",
        "VARCHAR",
        "自動編號：IN-{供應商}-000",
        ["進貨單號"],
        writable=False,
    ),
    make_field(
        "ERP48_PURCHASE_ORDER",
        "1023123",
        "日期",
        "DATE",
        "預設值：$DATE",
        ["進貨日期"],
        writable=True,
    ),
    make_field(
        "ERP48_PURCHASE_ORDER",
        "1023126",
        "收貨日期",
        "DATE",
        "收貨完成日期",
        ["收貨日"],
        writable=False,
    ),
    make_field(
        "ERP48_PURCHASE_ORDER",
        "1023162",
        "更新採購單狀態",
        "VARCHAR",
        "已進貨完成/未進貨完成",
        ["狀態"],
        writable=True,
    ),
    make_field(
        "ERP48_PURCHASE_ORDER",
        "1023124",
        "來源採購單號",
        "VARCHAR",
        "唯讀：載入採購單",
        ["採購單"],
        writable=False,
    ),
    make_field(
        "ERP48_PURCHASE_ORDER",
        "1023125",
        "收貨單號",
        "VARCHAR",
        "唯讀：載入收貨單",
        ["收貨單"],
        writable=False,
    ),
    make_field(
        "ERP48_PURCHASE_ORDER",
        "1023139",
        "未稅金額",
        "DECIMAL",
        "未稅總金額",
        ["未稅金額"],
        writable=True,
    ),
    make_field(
        "ERP48_PURCHASE_ORDER",
        "1023140",
        "課稅別",
        "VARCHAR",
        "課稅類別",
        ["課稅別"],
        writable=True,
    ),
    make_field(
        "ERP48_PURCHASE_ORDER",
        "1023141",
        "折扣金額",
        "DECIMAL",
        "折扣金額",
        ["折扣"],
        writable=True,
    ),
    make_field(
        "ERP48_PURCHASE_ORDER",
        "1023142",
        "稅率",
        "DECIMAL",
        "稅率百分比",
        ["稅率"],
        writable=True,
    ),
    make_field(
        "ERP48_PURCHASE_ORDER",
        "1023143",
        "折扣%數",
        "DECIMAL",
        "折扣百分比",
        ["折扣%"],
        writable=True,
    ),
    make_field(
        "ERP48_PURCHASE_ORDER",
        "1023144",
        "稅額",
        "DECIMAL",
        "稅額",
        ["稅額"],
        writable=True,
    ),
    make_field(
        "ERP48_PURCHASE_ORDER",
        "1023147",
        "運費",
        "DECIMAL",
        "運費",
        ["運費"],
        writable=True,
    ),
    make_field(
        "ERP48_PURCHASE_ORDER",
        "1023148",
        "含稅總計",
        "DECIMAL",
        "含稅總金額",
        ["總金額"],
        writable=True,
    ),
    make_field(
        "ERP48_PURCHASE_ORDER",
        "1024650",
        "發票號碼",
        "VARCHAR",
        "統一發票號碼",
        ["發票"],
        writable=True,
    ),
    make_field(
        "ERP48_PURCHASE_ORDER",
        "1024656",
        "未稅金額(載入)",
        "DECIMAL",
        "唯讀：載入計算",
        [],
        writable=False,
    ),
    make_field(
        "ERP48_PURCHASE_ORDER",
        "1024657",
        "折扣金額(載入)",
        "DECIMAL",
        "唯讀：載入",
        [],
        writable=False,
    ),
    make_field(
        "ERP48_PURCHASE_ORDER",
        "1024658",
        "折扣%數(載入)",
        "DECIMAL",
        "唯讀：載入",
        [],
        writable=False,
    ),
    make_field(
        "ERP48_PURCHASE_ORDER",
        "1024660",
        "課稅別(載入)",
        "VARCHAR",
        "唯讀：載入",
        [],
        writable=False,
    ),
    make_field(
        "ERP48_PURCHASE_ORDER",
        "1024661",
        "稅率(載入)",
        "DECIMAL",
        "唯讀：載入",
        [],
        writable=False,
    ),
    make_field(
        "ERP48_PURCHASE_ORDER",
        "1024662",
        "稅額(載入)",
        "DECIMAL",
        "唯讀：載入",
        [],
        writable=False,
    ),
    make_field(
        "ERP48_PURCHASE_ORDER",
        "1024663",
        "運費(載入)",
        "DECIMAL",
        "唯讀：載入",
        [],
        writable=False,
    ),
    make_field(
        "ERP48_PURCHASE_ORDER",
        "1024664",
        "含稅總計(載入)",
        "DECIMAL",
        "唯讀：載入",
        [],
        writable=False,
    ),
    # 供應商連結
    fk_field(
        "ERP48_PURCHASE_ORDER",
        "1023121",
        "供應商編碼",
        "供應商編號",
        ["供應商"],
        relation_table="CFG10_VENDOR",
        relation_field="1015577",
        writable=False,
    ),
    make_field(
        "ERP48_PURCHASE_ORDER",
        "1023122",
        "供應商名稱",
        "VARCHAR",
        "唯讀：載入供應商名稱",
        [],
        writable=False,
    ),
]
fields.extend(ERP48_FIELDS)

# 子表格：進貨明細 (1023150)
ERP48_ITEM_SUB = [
    make_field(
        "ERP48_PURCHASE_ORDER",
        "1023127",
        "原材料廠商自編碼",
        "VARCHAR",
        "唯讀：載入供應商自編",
        [],
        writable=False,
        is_subtable=True,
        subtable_key="1023150",
    ),
    make_field(
        "ERP48_PURCHASE_ORDER",
        "1023130",
        "採購數量",
        "DECIMAL",
        "採購數量",
        ["數量"],
        writable=False,
        is_subtable=True,
        subtable_key="1023150",
    ),
    make_field(
        "ERP48_PURCHASE_ORDER",
        "1023131",
        "收貨數量",
        "DECIMAL",
        "實際收貨數量",
        ["收貨"],
        writable=True,
        is_subtable=True,
        subtable_key="1023150",
    ),
    make_field(
        "ERP48_PURCHASE_ORDER",
        "1023132",
        "數量單位",
        "VARCHAR",
        "單位",
        ["單位"],
        writable=False,
        is_subtable=True,
        subtable_key="1023150",
    ),
    make_field(
        "ERP48_PURCHASE_ORDER",
        "1023133",
        "單價",
        "DECIMAL",
        "單價",
        ["單價"],
        writable=True,
        is_subtable=True,
        subtable_key="1023150",
    ),
    make_field(
        "ERP48_PURCHASE_ORDER",
        "1023134",
        "小計",
        "DECIMAL",
        "金額小計",
        ["小計"],
        writable=True,
        is_subtable=True,
        subtable_key="1023150",
    ),
    make_field(
        "ERP48_PURCHASE_ORDER",
        "1023135",
        "批號",
        "VARCHAR",
        "批號",
        ["批號"],
        writable=True,
        is_subtable=True,
        subtable_key="1023150",
    ),
    make_field(
        "ERP48_PURCHASE_ORDER",
        "1023136",
        "有效日期",
        "DATE",
        "有效期限",
        ["效期"],
        writable=True,
        is_subtable=True,
        subtable_key="1023150",
    ),
    make_field(
        "ERP48_PURCHASE_ORDER",
        "1023137",
        "包裝規格",
        "VARCHAR",
        "包裝規格",
        ["規格"],
        writable=True,
        is_subtable=True,
        subtable_key="1023150",
    ),
    make_field(
        "ERP48_PURCHASE_ORDER",
        "1023138",
        "包裝規格單位",
        "VARCHAR",
        "包裝單位",
        ["單位"],
        writable=True,
        is_subtable=True,
        subtable_key="1023150",
    ),
    make_field(
        "ERP48_PURCHASE_ORDER",
        "1023153",
        "退貨",
        "VARCHAR",
        "勾選：No/Yes",
        ["退貨"],
        writable=True,
        is_subtable=True,
        subtable_key="1023150",
    ),
    make_field(
        "ERP48_PURCHASE_ORDER",
        "1023154",
        "退貨數量",
        "DECIMAL",
        "退貨數量",
        ["退貨"],
        writable=True,
        is_subtable=True,
        subtable_key="1023150",
    ),
    make_field(
        "ERP48_PURCHASE_ORDER",
        "1023151",
        "年月",
        "VARCHAR",
        "年月（yyyy/MM）",
        ["年月"],
        writable=True,
        is_subtable=True,
        subtable_key="1023150",
    ),
    # 品項連結
    fk_field(
        "ERP48_PURCHASE_ORDER",
        "1023128",
        "品項編碼",
        "品項編碼",
        ["品項", "料號"],
        relation_table="CFG9_ITEM",
        relation_field="1015229",
        writable=False,
        is_subtable=True,
        subtable_key="1023150",
    ),
    make_field(
        "ERP48_PURCHASE_ORDER",
        "1023129",
        "品項名稱",
        "VARCHAR",
        "唯讀：載入品項名稱",
        [],
        writable=False,
        is_subtable=True,
        subtable_key="1023150",
    ),
]
fields.extend(ERP48_ITEM_SUB)

# ===========================================================================
# §3 TABLE RELATIONS
# ===========================================================================

relations = [
    # 組織部門 ← 員工（多）
    {
        "_key": "REL_CFG7_CFG2",
        "relation_id": "REL_CFG7_CFG2",
        "left_table": "CFG7_EMPLOYEE",
        "left_field": "1015495",
        "right_table": "CFG2_DEPT",
        "right_field": "1015391",
        "join_type": "LEFT",
        "cardinality": "N:1",
        "confidence": 1.0,
    },
    # 員工 → 代理人（員工自身）
    {
        "_key": "REL_CFG7_SELF",
        "relation_id": "REL_CFG7_SELF",
        "left_table": "CFG7_EMPLOYEE",
        "left_field": "1015500",
        "right_table": "CFG7_EMPLOYEE",
        "right_field": "1015428",
        "join_type": "LEFT",
        "cardinality": "N:1",
        "confidence": 0.95,
    },
    # 品項 → 主供應商
    {
        "_key": "REL_CFG9_CFG10",
        "relation_id": "REL_CFG9_CFG10",
        "left_table": "CFG9_ITEM",
        "left_field": "1022528",
        "right_table": "CFG10_VENDOR",
        "right_field": "1015577",
        "join_type": "LEFT",
        "cardinality": "N:1",
        "confidence": 1.0,
    },
    # 進貨單 → 供應商
    {
        "_key": "REL_ERP48_CFG10",
        "relation_id": "REL_ERP48_CFG10",
        "left_table": "ERP48_PURCHASE_ORDER",
        "left_field": "1023121",
        "right_table": "CFG10_VENDOR",
        "right_field": "1015577",
        "join_type": "LEFT",
        "cardinality": "N:1",
        "confidence": 1.0,
    },
    # 進貨明細 → 進貨單（表頭）
    {
        "_key": "REL_ERP48_ITEM",
        "relation_id": "REL_ERP48_ITEM",
        "left_table": "ERP48_PURCHASE_ORDER",
        "left_field": "1023120",
        "right_table": "ERP48_PURCHASE_ORDER",
        "right_field": "1023120",
        "join_type": "INNER",
        "cardinality": "1:N",
        "confidence": 1.0,
    },
    # 進貨明細 → 品項
    {
        "_key": "REL_ERP48_CFG9",
        "relation_id": "REL_ERP48_CFG9",
        "left_table": "ERP48_PURCHASE_ORDER",
        "left_field": "1023128",
        "right_table": "CFG9_ITEM",
        "right_field": "1015229",
        "join_type": "LEFT",
        "cardinality": "N:1",
        "confidence": 1.0,
    },
    # 進貨明細 → 供應商
    {
        "_key": "REL_ERP48_ITEM_CFG10",
        "relation_id": "REL_ERP48_ITEM_CFG10",
        "left_table": "ERP48_PURCHASE_ORDER",
        "left_field": "1023127",
        "right_table": "CFG10_VENDOR",
        "right_field": "1015577",
        "join_type": "LEFT",
        "cardinality": "N:1",
        "confidence": 0.95,
    },
    # 部門子表格員工 → 代理人
    {
        "_key": "REL_CFG2_SUB_EMP",
        "relation_id": "REL_CFG2_SUB_EMP",
        "left_table": "CFG2_DEPT",
        "left_field": "1015500",
        "right_table": "CFG7_EMPLOYEE",
        "right_field": "1015428",
        "join_type": "LEFT",
        "cardinality": "N:1",
        "confidence": 0.9,
    },
]

# ===========================================================================
# §4 Add timestamps to all records
# ===========================================================================

for f in fields:
    f["created_at"] = TS
    f["updated_at"] = TS

for r in relations:
    r["status"] = "enabled"
    r["created_at"] = TS
    r["updated_at"] = TS

# ===========================================================================
# §5 Main
# ===========================================================================

if __name__ == "__main__":
    print(f"\n{'=' * 60}")
    print("Seeding Ragic Phase 1 Schema → ArangoDB (_ragic collections)")
    print(f"{'=' * 60}")

    print(f"\n[da_table_info_ragic — {len(tables)} tables]")
    insert_batch("da_table_info_ragic", tables, "da_table_info_ragic")

    print(f"\n[da_field_info_ragic — {len(fields)} fields]")
    insert_batch("da_field_info_ragic", fields, "da_field_info_ragic")

    print(f"\n[da_table_relation_ragic — {len(relations)} relations]")
    insert_batch("da_table_relation_ragic", relations, "da_table_relation_ragic")

    print(f"\n{'=' * 60}")
    print("✅ Ragic Phase 1 Schema seeding complete!")
    print(f"   Tables:     {len(tables)}")
    print(f"   Fields:     {len(fields)}")
    print(f"   Relations:  {len(relations)}")
    print(
        "   Collections: da_table_info_ragic, da_field_info_ragic, da_table_relation_ragic"
    )
    print(f"{'=' * 60}")
