/**
 * @file        Icon 映射工具
 * @description Ant Design Icons 映射，用於功能選單圖示
 * @lastUpdate  2026-03-18 04:50:00
 * @author      Daniel Chung
 * @version     1.0.0
 */

import React from 'react';
import {
  MenuFoldOutlined,
  MenuUnfoldOutlined,
  UserOutlined,
  TeamOutlined,
  SettingOutlined,
  LogoutOutlined,
  SunOutlined,
  MoonOutlined,
  DesktopOutlined,
  ToolOutlined,
  DatabaseOutlined,
  SearchOutlined,
  TableOutlined,
  FileOutlined,
  FolderOutlined,
  LaptopOutlined,
  MobileOutlined,
  CloudServerOutlined,
  GlobalOutlined,
  CalendarOutlined,
  ClockCircleOutlined,
  BellOutlined,
  MailOutlined,
  MessageOutlined,
  StarOutlined,
  HeartOutlined,
  LikeOutlined,
  DislikeOutlined,
  CheckCircleOutlined,
  CloseCircleOutlined,
  InfoCircleOutlined,
  ExclamationCircleOutlined,
  QuestionCircleOutlined,
  LockOutlined,
  UnlockOutlined,
  KeyOutlined,
  SafetyOutlined,
  EyeOutlined,
  EyeInvisibleOutlined,
  UploadOutlined,
  DownloadOutlined,
  ShareAltOutlined,
  LinkOutlined,
  PaperClipOutlined,
  CopyOutlined,
  ScissorOutlined,
  DeleteOutlined,
  SaveOutlined,
  PrinterOutlined,
  PlusOutlined,
  MinusOutlined,
  CloseOutlined,
  ArrowUpOutlined,
  ArrowDownOutlined,
  ArrowLeftOutlined,
  ArrowRightOutlined,
  EnterOutlined,
  SwapOutlined,
  ReloadOutlined,
  SyncOutlined,
  PoweroffOutlined,
  HomeOutlined,
  BankOutlined,
  ShopOutlined,
  ShoppingCartOutlined,
  BugOutlined,
  CodeOutlined,
  CodeSandboxOutlined,
  ContainerOutlined,
  AppstoreOutlined,
  ChromeOutlined,
  SlidersOutlined,
  PieChartOutlined,
  BarChartOutlined,
  LineChartOutlined,
  AreaChartOutlined,
  RadarChartOutlined,
  FundOutlined,
  DashboardOutlined,
  FundProjectionScreenOutlined,
  BuildOutlined,
  ExperimentOutlined,
  RobotOutlined,
  ThunderboltOutlined,
  FireOutlined,
  HddOutlined,
  CloudOutlined,
  VideoCameraOutlined,
  SoundOutlined,
  PictureOutlined,
  CameraOutlined,
  EnvironmentOutlined,
  SkinOutlined,
  BgColorsOutlined,
  FontSizeOutlined,
  BoldOutlined,
  ItalicOutlined,
  UnderlineOutlined,
  StrikethroughOutlined,
  OrderedListOutlined,
  UnorderedListOutlined,
  AlignLeftOutlined,
  AlignCenterOutlined,
  AlignRightOutlined,
  FullscreenOutlined,
  FullscreenExitOutlined,
  ZoomInOutlined,
  ZoomOutOutlined,
  DragOutlined,
  SelectOutlined,
  AuditOutlined,
  BlockOutlined,
  BorderOutlined,
  CompressOutlined,
  ExpandOutlined,
  FilterOutlined,
  SortAscendingOutlined,
  SortDescendingOutlined,
  HolderOutlined,
  SnippetsOutlined,
  HighlightOutlined,
  FontColorsOutlined,
  ConsoleSqlOutlined,
  FunctionOutlined,
  ControlOutlined,
  LayoutOutlined,
  MenuOutlined,
  WindowsOutlined,
  ApartmentOutlined,
  BorderTopOutlined,
  BorderBottomOutlined,
  BorderLeftOutlined,
  BorderRightOutlined,
  ColumnWidthOutlined,
  ColumnHeightOutlined,
  CheckSquareOutlined,
  FolderOpenOutlined,
  FileExcelOutlined,
  FileWordOutlined,
  FilePdfOutlined,
  FileTextOutlined,
  FileUnknownOutlined,
  FileAddOutlined,
  FolderAddOutlined,
  CloudUploadOutlined,
  CloudDownloadOutlined,
  InboxOutlined,
  ForwardOutlined,
  SwapLeftOutlined,
  SwapRightOutlined,
  PlayCircleOutlined,
  PauseCircleOutlined,
  StepBackwardOutlined,
  StepForwardOutlined,
  FastBackwardOutlined,
  FastForwardOutlined,
  ShrinkOutlined,
  ArrowsAltOutlined,
  DownOutlined,
  UpOutlined,
  LeftOutlined,
  RightOutlined,
  MinusCircleOutlined,
  PlusCircleOutlined,
  ClearOutlined,
  RadiusSettingOutlined,
  RedoOutlined,
  UndoOutlined,
  DoubleLeftOutlined,
  DoubleRightOutlined,
  VerticalLeftOutlined,
  VerticalRightOutlined,
  VerticalAlignTopOutlined,
  VerticalAlignMiddleOutlined,
  VerticalAlignBottomOutlined,
  TrophyOutlined,
  GoldOutlined,
  CrownOutlined,
  SmileOutlined,
  MehOutlined,
  FrownOutlined,
  RightCircleOutlined,
  LeftCircleOutlined,
  PlaySquareOutlined,
  HistoryOutlined,
  RollbackOutlined,
  RetweetOutlined,
  ImportOutlined,
  ExportOutlined,
  RocketOutlined,
  ProjectOutlined,
  PlusSquareOutlined,
  BookOutlined,
  ReadOutlined,
} from '@ant-design/icons';

export type IconName = string;

export const iconMap: Record<IconName, React.FC<any>> = {
  MenuFoldOutlined,
  MenuUnfoldOutlined,
  UserOutlined,
  TeamOutlined,
  SettingOutlined,
  LogoutOutlined,
  SunOutlined,
  MoonOutlined,
  DesktopOutlined,
  ToolOutlined,
  DatabaseOutlined,
  SearchOutlined,
  TableOutlined,
  FileOutlined,
  FolderOutlined,
  LaptopOutlined,
  MobileOutlined,
  CloudServerOutlined,
  GlobalOutlined,
  CalendarOutlined,
  ClockCircleOutlined,
  BellOutlined,
  MailOutlined,
  MessageOutlined,
  StarOutlined,
  HeartOutlined,
  LikeOutlined,
  DislikeOutlined,
  CheckCircleOutlined,
  CloseCircleOutlined,
  InfoCircleOutlined,
  ExclamationCircleOutlined,
  QuestionCircleOutlined,
  LockOutlined,
  UnlockOutlined,
  KeyOutlined,
  SafetyOutlined,
  EyeOutlined,
  EyeInvisibleOutlined,
  UploadOutlined,
  DownloadOutlined,
  ShareAltOutlined,
  LinkOutlined,
  PaperClipOutlined,
  CopyOutlined,
  ScissorOutlined,
  DeleteOutlined,
  SaveOutlined,
  PrinterOutlined,
  PlusOutlined,
  MinusOutlined,
  CloseOutlined,
  ArrowUpOutlined,
  ArrowDownOutlined,
  ArrowLeftOutlined,
  ArrowRightOutlined,
  EnterOutlined,
  SwapOutlined,
  ReloadOutlined,
  SyncOutlined,
  PoweroffOutlined,
  HomeOutlined,
  BankOutlined,
  ShopOutlined,
  ShoppingCartOutlined,
  BugOutlined,
  CodeOutlined,
  CodeSandboxOutlined,
  ContainerOutlined,
  AppstoreOutlined,
  ChromeOutlined,
  SlidersOutlined,
  PieChartOutlined,
  BarChartOutlined,
  LineChartOutlined,
  AreaChartOutlined,
  RadarChartOutlined,
  FundOutlined,
  DashboardOutlined,
  FundProjectionScreenOutlined,
  BuildOutlined,
  ExperimentOutlined,
  RobotOutlined,
  ThunderboltOutlined,
  FireOutlined,
  HddOutlined,
  CloudOutlined,
  VideoCameraOutlined,
  SoundOutlined,
  PictureOutlined,
  CameraOutlined,
  EnvironmentOutlined,
  SkinOutlined,
  BgColorsOutlined,
  FontSizeOutlined,
  BoldOutlined,
  ItalicOutlined,
  UnderlineOutlined,
  StrikethroughOutlined,
  OrderedListOutlined,
  UnorderedListOutlined,
  AlignLeftOutlined,
  AlignCenterOutlined,
  AlignRightOutlined,
  FullscreenOutlined,
  FullscreenExitOutlined,
  ZoomInOutlined,
  ZoomOutOutlined,
  DragOutlined,
  SelectOutlined,
  AuditOutlined,
  BlockOutlined,
  BorderOutlined,
  CompressOutlined,
  ExpandOutlined,
  FilterOutlined,
  SortAscendingOutlined,
  SortDescendingOutlined,
  HolderOutlined,
  SnippetsOutlined,
  HighlightOutlined,
  FontColorsOutlined,
  ConsoleSqlOutlined,
  FunctionOutlined,
  ControlOutlined,
  LayoutOutlined,
  MenuOutlined,
  WindowsOutlined,
  ApartmentOutlined,
  BorderTopOutlined,
  BorderBottomOutlined,
  BorderLeftOutlined,
  BorderRightOutlined,
  ColumnWidthOutlined,
  ColumnHeightOutlined,
  CheckSquareOutlined,
  FolderOpenOutlined,
  FileExcelOutlined,
  FileWordOutlined,
  FilePdfOutlined,
  FileTextOutlined,
  FileUnknownOutlined,
  FileAddOutlined,
  FolderAddOutlined,
  CloudUploadOutlined,
  CloudDownloadOutlined,
  InboxOutlined,
  ForwardOutlined,
  SwapLeftOutlined,
  SwapRightOutlined,
  PlayCircleOutlined,
  PauseCircleOutlined,
  StepBackwardOutlined,
  StepForwardOutlined,
  FastBackwardOutlined,
  FastForwardOutlined,
  ShrinkOutlined,
  ArrowsAltOutlined,
  DownOutlined,
  UpOutlined,
  LeftOutlined,
  RightOutlined,
  MinusCircleOutlined,
  PlusCircleOutlined,
  ClearOutlined,
  RadiusSettingOutlined,
  RedoOutlined,
  UndoOutlined,
  DoubleLeftOutlined,
  DoubleRightOutlined,
  VerticalLeftOutlined,
  VerticalRightOutlined,
  VerticalAlignTopOutlined,
  VerticalAlignMiddleOutlined,
  VerticalAlignBottomOutlined,
  TrophyOutlined,
  GoldOutlined,
  CrownOutlined,
  SmileOutlined,
  MehOutlined,
  FrownOutlined,
  RightCircleOutlined,
  LeftCircleOutlined,
  PlaySquareOutlined,
  HistoryOutlined,
  RollbackOutlined,
  RetweetOutlined,
  ImportOutlined,
  ExportOutlined,
  RocketOutlined,
  ProjectOutlined,
  PlusSquareOutlined,
  BookOutlined,
  ReadOutlined,
};

export const ANT_DESIGN_ICONS = [
  { value: 'RobotOutlined', label: '機器人' },
  { value: 'SettingOutlined', label: '設置' },
  { value: 'UserOutlined', label: '用戶' },
  { value: 'TeamOutlined', label: '團隊' },
  { value: 'ToolOutlined', label: '工具' },
  { value: 'MenuOutlined', label: '菜單' },
  { value: 'FileOutlined', label: '文件' },
  { value: 'FolderOutlined', label: '文件夾' },
  { value: 'DatabaseOutlined', label: '數據庫' },
  { value: 'DesktopOutlined', label: '桌面' },
  { value: 'GlobalOutlined', label: '地球' },
  { value: 'SearchOutlined', label: '搜索' },
  { value: 'TableOutlined', label: '表格' },
  { value: 'CalendarOutlined', label: '日曆' },
  { value: 'ClockCircleOutlined', label: '時鐘' },
  { value: 'InboxOutlined', label: '收件箱' },
  { value: 'MailOutlined', label: '郵件' },
  { value: 'CloudServerOutlined', label: '雲服務' },
  { value: 'CodeOutlined', label: '代碼' },
  { value: 'FileTextOutlined', label: '文檔' },
  { value: 'VideoCameraOutlined', label: '視頻' },
  { value: 'AudioOutlined', label: '音頻' },
  { value: 'PictureOutlined', label: '圖片' },
  { value: 'ShopOutlined', label: '商店' },
  { value: 'BankOutlined', label: '銀行' },
  { value: 'DollarOutlined', label: '美元' },
  { value: 'AccountBookOutlined', label: '帳本' },
  { value: 'BarChartOutlined', label: '圖表' },
  { value: 'PieChartOutlined', label: '餅圖' },
  { value: 'LineChartOutlined', label: '折線圖' },
  { value: 'DotChartOutlined', label: '點圖' },
  { value: 'RadarChartOutlined', label: '雷達圖' },
  { value: 'FundOutlined', label: '基金' },
  { value: 'SafetyCertificateOutlined', label: '安全證書' },
  { value: 'SecurityScanOutlined', label: '安全掃描' },
  { value: 'AlertOutlined', label: '警告' },
  { value: 'WarningOutlined', label: '注意' },
  { value: 'QuestionCircleOutlined', label: '問題' },
  { value: 'InfoCircleOutlined', label: '信息' },
  { value: 'CheckCircleOutlined', label: '完成' },
  { value: 'CloseCircleOutlined', label: '關閉' },
  { value: 'BulbOutlined', label: '燈泡' },
  { value: 'ExperimentOutlined', label: '實驗' },
  { value: 'RocketOutlined', label: '火箭' },
  { value: 'ThunderboltOutlined', label: '閃電' },
  { value: 'KeyOutlined', label: '密鑰' },
  { value: 'LockOutlined', label: '鎖' },
  { value: 'UnlockOutlined', label: '解鎖' },
  { value: 'SmileOutlined', label: '微笑' },
  { value: 'MehOutlined', label: '中性' },
  { value: 'FrownOutlined', label: '皺眉' },
  { value: 'HourglassOutlined', label: '沙漏' },
  { value: 'StopOutlined', label: '停止' },
  { value: 'PlayCircleOutlined', label: '播放' },
  { value: 'PauseCircleOutlined', label: '暫停' },
  { value: 'CustomerServiceOutlined', label: '客服' },
  { value: 'MessageOutlined', label: '消息' },
  { value: 'BellOutlined', label: '鈴鐺' },
  { value: 'ScheduleOutlined', label: '日程' },
  { value: 'PaperClipOutlined', label: '附件' },
  { value: 'LinkOutlined', label: '鏈接' },
  { value: 'ShareAltOutlined', label: '分享' },
  { value: 'DownloadOutlined', label: '下載' },
  { value: 'UploadOutlined', label: '上傳' },
  { value: 'SaveOutlined', label: '保存' },
  { value: 'DeleteOutlined', label: '刪除' },
  { value: 'EditOutlined', label: '編輯' },
  { value: 'CopyOutlined', label: '複製' },
  { value: 'ScissorOutlined', label: '剪裁' },
  { value: 'FontSizeOutlined', label: '字體' },
  { value: 'BoldOutlined', label: '粗體' },
  { value: 'ItalicOutlined', label: '斜體' },
  { value: 'UnderlineOutlined', label: '下劃線' },
  { value: 'HighlightOutlined', label: '高亮' },
  { value: 'OrderedListOutlined', label: '有序列表' },
  { value: 'UnorderedListOutlined', label: '無序列表' },
  { value: 'ColumnWidthOutlined', label: '列寬' },
  { value: 'RowHeightOutlined', label: '行高' },
  { value: 'BorderOutlined', label: '邊框' },
  { value: 'AlignLeftOutlined', label: '左對齊' },
  { value: 'AlignCenterOutlined', label: '居中' },
  { value: 'AlignRightOutlined', label: '右對齊' },
  { value: 'ApartmentOutlined', label: '公寓' },
  { value: 'AuditOutlined', label: '審計' },
  { value: 'FileDoneOutlined', label: '文件完成' },
  { value: 'FileProtectOutlined', label: '文件保護' },
  { value: 'FileSearchOutlined', label: '文件搜索' },
  { value: 'SolutionOutlined', label: '解決方案' },
  { value: 'ProjectOutlined', label: '項目' },
  { value: 'BookOutlined', label: '書籍' },
  { value: 'ReadOutlined', label: '閱讀' },
  { value: 'HistoryOutlined', label: '歷史' },
  { value: 'WalletOutlined', label: '錢包' },
  { value: 'CreditCardOutlined', label: '信用卡' },
  { value: 'ShoppingCartOutlined', label: '購物車' },
  { value: 'RiseOutlined', label: '上升' },
  { value: 'FallOutlined', label: '下降' },
  { value: 'StockOutlined', label: '股票' },
];

export function getIconComponent(iconName: string | null | undefined): React.FC<any> | null {
  if (!iconName) return null;
  return iconMap[iconName] || null;
}
